// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLGdPBT9tQ0XoQIbpBE6cJlBmjgBPlqM',
    appId: '1:443923969735:web:b6fd25fd46de7bff82f0e2',
    messagingSenderId: '443923969735',
    projectId: 'meragi-5484d',
    authDomain: 'meragi-5484d.firebaseapp.com',
    storageBucket: 'meragi-5484d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCxenvOrqjXaB_5IRee7yCzLwFiq-LcpI',
    appId: '1:443923969735:android:c1a29efd7dc9f1b882f0e2',
    messagingSenderId: '443923969735',
    projectId: 'meragi-5484d',
    storageBucket: 'meragi-5484d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAya_e9fDe0lrI-zppMvdvrRAgRO2K9rvA',
    appId: '1:443923969735:ios:e89d2bc89966f4f282f0e2',
    messagingSenderId: '443923969735',
    projectId: 'meragi-5484d',
    storageBucket: 'meragi-5484d.appspot.com',
    iosBundleId: 'com.example.meragiAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAya_e9fDe0lrI-zppMvdvrRAgRO2K9rvA',
    appId: '1:443923969735:ios:e89d2bc89966f4f282f0e2',
    messagingSenderId: '443923969735',
    projectId: 'meragi-5484d',
    storageBucket: 'meragi-5484d.appspot.com',
    iosBundleId: 'com.example.meragiAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtLGdPBT9tQ0XoQIbpBE6cJlBmjgBPlqM',
    appId: '1:443923969735:web:1e7356dcbb66ff7282f0e2',
    messagingSenderId: '443923969735',
    projectId: 'meragi-5484d',
    authDomain: 'meragi-5484d.firebaseapp.com',
    storageBucket: 'meragi-5484d.appspot.com',
  );
}
